### ISSUE TITLE
Node-Red, Docker, Traefik

### ISSUE THREAD

**Issue by ToeiRei** [datech/node-red-contrib-amazon-echo#84]
##### SUMMARY

Trying to get it all running on one docker host using traefik to proxy the services

##### ECHO DEVICES
* Echo Dot 3rd generation

##### MODULE VERSION

```
node-red
1.0.3
node-red-contrib-amazon-echo
0.1.9
node-red-contrib-home-assistant-websocket
0.16.3
node-red-node-rbe
0.2.5
node-red-node-tail
0.0.3
```

##### CONFIGURATION

docker-compose.yaml

```
  node-red:
     image: nodered/node-red:latest
     volumes:
       - type: volume
         source: nodered-data
         target: /data
     environment:
       - TS=Europe/Vienna
     labels:
        - "traefik.enable=true"
        - "traefik.admin.frontend.rule=Host:${NODERED_HOSTNAME}"
        - "traefik.admin.port=1880"
        - "traefik.admin.backend=backend-node-red-lan-admin"
     networks:
      - traefik_proxy
```

That's the basic node-red setup which actually works for anything but node-red-contrib-amazon-echo. Due to the nature of rancherOS, my containers are not able to run as root. Any ideas?

**Comment by Barabba11** [comment]
maybe you have th port 80 already used from webskocket.
Alexa will search only on port 80, so it should be used by this module. Try to make it free. Use iptables to NAT under linux, it's easy and efficent

**Comment by ToeiRei** [comment]
That doesn't work due to traefik needed there


Am 23.11.2019 10:56 schrieb Barabba11 <notifications@github.com>:
maybe you have th port 80 already used from webskocket.
Alexa will search only on port 80, so it should be used by this module. Try to make it free. Use iptables to NAT under linux, it's easy and efficent

**Comment by stklcode** [comment]
If you got Traefik running, _you_ can control the routes...

In the end, your Echo has to reach the emulated Hue API through port 80. Internally it can be any port you like.

There are many solutions to get there. Just to mention the most obvious ones:
* use multiple hostnames (admin.example.com, api.example.com, nodered.example.com) and expose each service on one of them
* assign multiple ip address to your NIC and run two instances each on 80
* with only a single hostname/ip
  * route only traffic from Echo devices to the API, all other traffic to whatever runs on 80 or
  * route only requests to `.../api/` subpath to the API

If it's only _NodeRed_ and the emulated Hub you're running, just run _NodeRed_ on _1880_ and the hub on let's say _1881_. Configure two frontends and two backends with _Traefik_ and assign the route with, s.t. both can be accessed on _80_ externally.

My home automation setup has a total of 12 hostnames exposed throguh a single reverse proxy (all accessible through 80/443 externally), one of them is _nodered.my-device_ and one is _hue.my-device_. Works perfectly.

**Comment by ToeiRei** [comment]
I'll give it a shot as I want to get rid of as many external services as possible.

**Comment by ToeiRei** [comment]
@stklcode looks like traefik is giving me more headache than anticipated. Mind helping me out with its config?

**Comment by ToeiRei** [comment]
peeking around in the docker container I found the service listening node-red-contrib-amazon-echo hub to ipv6 only

```
bash-5.0$ netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:39369        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:1880            0.0.0.0:*               LISTEN      16/node-red
tcp        0      0 172.21.0.6:53744        10.0.0.7:443            ESTABLISHED 16/node-red
tcp        0      0 127.0.0.1:43640         127.0.0.1:1880          TIME_WAIT   -
tcp        0      0 172.21.0.6:47060        96.126.109.223:8883     ESTABLISHED 16/node-red
tcp        0      0 172.21.0.6:52140        172.16.17.2:3000        ESTABLISHED 16/node-red
tcp        0      0 :::8080                 :::*                    LISTEN      16/node-red
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           16/node-red
udp        0      0 127.0.0.11:51836        0.0.0.0:*                           -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
```

is this intended/required as I do not run ipv6 in my lan

**Comment by stklcode** [comment]
> peeking around in the docker container I found the service listening node-red-contrib-amazon-echo hub to ipv6 only

Nope, it's listening on *any* address, as `:::8080` is simply wildcard in v6 notation.
That's fine and the service is reachable on any v4 address (if you don't believe me, simply try it and issue a request to `127.0.0.1:80` or ),

Whatever your problem is, it's not this.

> is this intended/required as I do not run ipv6 in my lan

Your container has IPv6 support, at least for link-local connections (default on about any modern linux unless explicitly disabled). And as you're running on Docker, the Docker bridge interface in default configuration assigns link-local addresses from the `fe80::/64` subnet along with a v4 subnet within `172.16/12` to all containers.
You may not be actively using it, but you definitely got IPv6 links.

**Comment by ToeiRei** [comment]
I've tried to work around the port 80 dilemma and came up with that:

```
  node-red:
     image: nodered/node-red:latest
     volumes:
       - type: volume
         source: nodered-data
         target: /data
     ports:
     - "8300:8300"
     environment:
       - TS=Europe/Vienna
     labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nodered.entrypoints=http"
        - "traefik.http.routers.nodered.rule=Host(`${NODERED_IP}`)"

        - "traefik.http.routers.nodered-secure.tls=true"
        - "traefik.http.routers.nodered-secure.entryPoints=https"
        - "traefik.http.routers.nodered-secure.rule=Host(`${NODERED_HOSTNAME}`)"

        - "traefik.http.routers.nodered.service=nodered"
        - "traefik.http.services.nodered.loadbalancer.server.port=8300"
        - "traefik.http.routers.nodered-secure.service=nodered-secure"
        - "traefik.http.services.nodered-secure.loadbalancer.server.port=1880"
```

but still, I cannot get it to work. @stklcode mind sharing your way of doing it?
